image: marvinmenzerath/latex

before_script:
    - apt-get update -qy
    - apt-get install -y python-dev python-pip
    - pip install Pygments

.build-tex:
  stage: build
  variables: 
    THESIS_STATUS: 'proposal' # 'proposal' or 'thesis'
    TEX_CMD: "latexmk -xelatex -latexoption='-shell-escape'"
  artifacts:
    paths:
      - ${TEX_DIR}/${TEX_JOB}.pdf
    expire_in: 1 mos
  script:
    - cd "${TEX_DIR}" && ${TEX_CMD} "${TEX_JOB}.tex"

build-thesis-text:
  variables: 
    TEX_DIR: '${THESIS_STATUS}/text'
    TEX_JOB: ${THESIS_STATUS}
  extends: .build-tex
    
build-thesis-slides:
  variables: 
    TEX_DIR: '${THESIS_STATUS}/presentation'
    TEX_JOB: 'slides'
  extends: .build-tex
